### PR TITLE
[release-v1.15] Fix e2e tests

### PR DESCRIPTION
**Pull request by pierDipi**

### CODE REVIEW

**Comment by pierDipi** [comment]
```
    logger.go:146: 2024-09-16T18:44:02.668Z	FATAL	environment/magic.go:243	failed to install CA certificates and issuer: failed to create resource certificates.cert-manager.io "selfsigned-ca" already exists - Resource:
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: selfsigned-ca
          namespace: serverless-tests
        spec:
          commonName: selfsigned-ca
          isCA: true
          issuerRef:
            group: cert-manager.io
            kind: Issuer
            name: selfsigned-issuer
          privateKey:
            algorithm: ECDSA
            size: 256
          secretName: eventshub-ca
        	{"test": "TestPingSourceDataPlane_BrokerAsSinkTLS"}
```

**Comment by pierDipi** [comment]
https://github.com/knative-extensions/reconciler-test/pull/759

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
