### PR TITLE
Upgrade to latest dependencies (#76)

### PR DESCRIPTION
**Pull request by serverless-qe**
* Run hack/update-deps.sh

* Use new `num-nodes` parameter

* Remove deprecated `skip-istio-addon` parameter

* Make linter happy

### CODE REVIEW

**Comment by creydr** [comment]
> @serverless-qe: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/prow/411-e2e-tests-aws-ocp-411	[f95850d](https://github.com/openshift-knative/eventing-istio/commit/f95850d01b4eb376e0fd85dfbe1e63e8cff6e56a)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_eventing-istio/61/pull-ci-openshift-knative-eventing-istio-release-next-411-e2e-tests-aws-ocp-411/1699221720176529408)	true	`/test 411-e2e-tests-aws-ocp-411`
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift-knative&repo=eventing-istio&pr=61). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:serverless-qe).

https://github.com/openshift-knative/eventing-istio/pull/62 should address it

**Comment by creydr** [comment]
seems Prow is having a bad time again.
```
Warning: Pull failed, retrying in 5s ...
error: build error: failed to pull image: After retrying 2 times, Pull image still failed due to error: reading signatures: ...
registry.ci.openshift.org/openshift/release: received unexpected HTTP status: 504 Gateway Time-out
```
Will retry later...

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
