### PR TITLE
[Automated] Update eventing-istio-eventing nightly (#364)

### PR DESCRIPTION
**Pull request by serverless-qe**
Update eventing nightly

Signed-off-by: Knative Automation <automation@knative.team>

### CODE REVIEW

**Comment by pierDipi** [comment]
```
quay.io/openshift/ci:openshift_release_rhel-8-release-golang-1.22-openshift-4.16" not found
```

**Comment by pierDipi** [comment]
```
{Failed  panic: test timed out after 1h0m0s
running tests:
	TestPingSourceDataPlane_BrokerAsSinkTLS (1h0m0s)
	TestPingSourceSendsEventsOIDC (1h0m0s)
	TestPingSourceTLS (1h0m0s)
	TestPingSourceWithCloudEventData (1h0m0s)
	TestPingSourceWithSinkRef (1h0m0s)
	TestPingSourceWithSinkURI (1h0m0s)
```

**Comment by pierDipi** [comment]
```
    Message:               Install failed with message: Job.batch "storage-version-migration-eventing-eventing-knative-nightly-1.34.0" is invalid: spec.template.labels: Invalid value: "storage-version-migration-eventing-eventing-knative-nightly-1.34.0": must be no more than 63 characters
```

**Comment by pierDipi** [comment]
```
{"level":"info","ts":"2024-08-09T01:53:56.097Z","logger":"knative-operator.manifestival","caller":"manifestival/manifestival.go:216","msg":"Updating","knative.dev/pod":"knative-operator-webhook-6f57554867-cgxsd","name":"knative-eventing/allow-kafka-webhook-eventing","type":"networking.k8s.io/v1, Kind=NetworkPolicy"}
panic: runtime error: slice bounds out of range [1:0]

goroutine 182 [running]:
knative.dev/operator/pkg/reconciler/knativeserving/ingress.GetIngressPath({0xc0025a7ff0, 0xf}, 0xc003705420)
	/go/src/github.com/openshift-knative/serverless-operator/vendor/knative.dev/operator/pkg/reconciler/knativeserving/ingress/ingress.go:65 +0x54f
knative.dev/operator/pkg/reconciler/manifests.Install({0x236e9e8?, 0xc00281c330?}, 0xc0037c7bc0?, {0x238a8a0, 0xc003286788})
	/go/src/github.com/openshift-knative/serverless-operator/vendor/knative.dev/operator/pkg/reconciler/manifests/install.go:40 +0x128
knative.dev/operator/pkg/reconciler/common.Stages.Execute(...)
	/go/src/github.com/openshift-knative/serverless-operator/vendor/knative.dev/operator/pkg/reconciler/common/stages.go:40
knative.dev/operator/pkg/reconciler/knativeeventing.(*Reconciler).ReconcileKind(0xc000208930, {0x236e9e8, 0xc00281c330}, 0xc003286788)
	/go/src/github.com/openshift-knative/serverless-operator/vendor/knative.dev/operator/pkg/reconciler/knativeeventing/knativeeventing.go:149 +0x7ca
knative.dev/operator/pkg/client/injection/reconciler/operator/v1beta1/knativeeventing.(*reconcilerImpl).Reconcile(0xc00046f2c0, {0x236e9e8, 0xc00281c300}, {0xc002bed260, 0x21})
	/go/src/github.com/openshift-knative/serverless-operator/vendor/knative.dev/operator/pkg/client/injection/reconciler/operator/v1beta1/knativeeventing/reconciler.go:236 +0x4f2
knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc0005d4840)
	/go/src/github.com/openshift-knative/serverless-operator/vendor/knative.dev/pkg/controller/controller.go:542 +0x508
knative.dev/pkg/controller.(*Impl).RunContext.func3()
	/go/src/github.com/openshift-knative/serverless-operator/vendor/knative.dev/pkg/controller/controller.go:491 +0x59
created by knative.dev/pkg/controller.(*Impl).RunContext in goroutine 201
	/go/src/github.com/openshift-knative/serverless-operator/vendor/knative.dev/pkg/controller/controller.go:489 +0x325
```

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
